# This is a basic workflow to help you get started with Actions

name: Create Badge Page

# Badge Page is updated when a new branch or tag is created.
# on delete is removed since it will be updated next branch creation.

# Controls when the workflow will run
on:
  create
  # delete  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-badge-page:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          # checkout 'badges' branch
          ref: 'badges'
          fetch-depth: 0

      - name: Generate a badge page
        # target of displayed workflows should match project's workflow
        run: |
          # bin/badge-maker.sh and bin/badge-markdown.sh are in badges branch
          ${PWD}/bin/badge-maker.sh ${GITHUB_REPOSITORY} "{{repository}}/actions/workflows/{{workflow}}/badge.svg?branch={{branch}}" blank.yml echo.yml > BADGES.md
          
      - name: Commit the page
        run: |
          git config --global user.name 'Badge Page Automatic Committer'
          git config --global user.email 'ywata@users.noreply.github.com'
          git add BADGES.md
          ([[ `git status --porcelain` ]] && git commit -m "Update badges" && git push)  || echo "No changes"
